[package]
name = "todo-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "todo-cli"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/bin/test.rs"

[dependencies]
bincode = "2.0.1"
clap = { version = "4.5.39", features = ["derive"] }
